services:
  bes-web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - 8000:8000
    depends_on:
      - bes-db
  bes-db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
