services:
  bes-app:
    build: .
    restart: unless-stopped
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://besshow:${DB_PASSWORD}@bes-db:5432/besshow
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - bes-db
    networks:
      - besshow-network

  bes-db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      - POSTGRES_DB=besshow
      - POSTGRES_USER=besshow
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - besshow-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - bes-app
    networks:
      - besshow-network

volumes:
  postgres_data:

networks:
  besshow-network:
    driver: bridge