# Generated by Django 5.2.5 on 2025-09-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanternWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='燈牆名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '燈牆',
                'verbose_name_plural': '燈牆管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanternPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='位置 (1-12)')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='序號')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='epd_management.lanternwall', verbose_name='所屬燈牆')),
            ],
            options={
                'verbose_name': '燈牆播放器',
                'verbose_name_plural': '燈牆播放器',
                'ordering': ['position'],
                'unique_together': {('wall', 'position')},
            },
        ),
    ]
