# Generated by Django 5.2.5 on 2025-09-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epd_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanternplayer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Player ID'),
        ),
    ]
