# Generated by Django 5.1.3 on 2025-09-02 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_county',
            field=models.CharField(blank=True, max_length=20, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='詳細地址'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_district',
            field=models.CharField(blank=True, max_length=20, verbose_name='鄉鎮市區'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='郵遞區號'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', '善男'), ('F', '信女'), ('O', '善信')], default='O', help_text='稱謂，用於疏文或感謝狀。', max_length=1, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gregorian_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='國曆生日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gregorian_birth_time',
            field=models.TimeField(blank=True, null=True, verbose_name='國曆出生時間'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lunar_birth_date',
            field=models.CharField(blank=True, max_length=30, verbose_name='農曆生日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lunar_birth_time',
            field=models.CharField(blank=True, default='吉時', max_length=10, verbose_name='農曆時辰'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='用於登入和接收通知。', max_length=20, null=True, unique=True, verbose_name='手機號碼'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='用於 API 的唯一識別碼，不可變更。', unique=True, verbose_name='公開識別碼'),
        ),
    ]
