# Generated by Django 5.2.5 on 2025-09-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_county_customuser_address_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bazi_day',
            field=models.CharField(blank=True, help_text='天干地支日柱，如丙午日', max_length=20, verbose_name='八字日柱'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bazi_month',
            field=models.CharField(blank=True, help_text='天干地支月柱，如乙巳月', max_length=20, verbose_name='八字月柱'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bazi_year',
            field=models.CharField(blank=True, help_text='天干地支年柱，如甲辰年', max_length=20, verbose_name='八字年柱'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zodiac_animal',
            field=models.CharField(blank=True, help_text='生肖動物，如龍', max_length=10, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lunar_birth_time',
            field=models.CharField(blank=True, default='吉時', max_length=20, verbose_name='農曆時辰'),
        ),
    ]
