# Generated by Django 5.2.5 on 2025-09-25 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='處理人員'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='處理完成時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_notes',
            field=models.TextField(blank=True, null=True, verbose_name='處理備註'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='處理開始時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_status',
            field=models.CharField(choices=[('pending', '未處理'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='處理狀態'),
        ),
    ]
