# Generated by Django 5.2.5 on 2025-09-25 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epd_management', '0002_alter_lanternplayer_serial_number'),
        ('orders', '0002_order_processed_by_order_processing_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemPlayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='配對時間')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='配對人員')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem', verbose_name='訂單項目')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epd_management.lanternplayer', verbose_name='播放器')),
            ],
            options={
                'verbose_name': '訂單項目播放器配對',
                'verbose_name_plural': '訂單項目播放器配對',
                'unique_together': {('order_item', 'player')},
            },
        ),
    ]
