# Generated by Django 5.2.5 on 2025-09-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitemplayerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_lanterns/', verbose_name='生成的圖片'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='圖片生成時間'),
        ),
    ]
