# Generated by Django 5.2.5 on 2025-09-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_generated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemplayerassignment',
            name='epd_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='EPD 設備 ID'),
        ),
        migrations.AddField(
            model_name='orderitemplayerassignment',
            name='upload_error',
            field=models.TextField(blank=True, null=True, verbose_name='上傳錯誤訊息'),
        ),
        migrations.AddField(
            model_name='orderitemplayerassignment',
            name='upload_status',
            field=models.CharField(choices=[('pending', '待上傳'), ('uploading', '上傳中'), ('completed', '已完成'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='上傳狀態'),
        ),
        migrations.AddField(
            model_name='orderitemplayerassignment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上傳完成時間'),
        ),
    ]
