# Generated by Django 5.2.5 on 2025-09-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitemplayerassignment_epd_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemplayerassignment',
            unique_together={('order_item', 'epd_id')},
        ),
    ]
