# Generated by Django 5.1.2 on 2025-09-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='燈種名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='燈種圖片')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
        ),
    ]
