# Generated by Django 5.2.5 on 2025-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prayer_text',
            field=models.TextField(blank=True, verbose_name='祈福語'),
        ),
    ]
